# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 600)
        MainWindow.setMinimumSize(QtCore.QSize(500, 600))
        MainWindow.setMaximumSize(QtCore.QSize(500, 600))
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(500, 600))
        self.centralwidget.setMaximumSize(QtCore.QSize(500, 600))
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 500, 600))
        self.tabWidget.setMinimumSize(QtCore.QSize(500, 600))
        self.tabWidget.setMaximumSize(QtCore.QSize(500, 600))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.tabWidget.setFont(font)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("font: 63 12pt \"Segoe UI Semibold\";\n"
"\n"
"")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setMinimumSize(QtCore.QSize(500, 600))
        self.tab.setMaximumSize(QtCore.QSize(500, 600))
        self.tab.setObjectName("tab")
        self.gridWidget = QtWidgets.QWidget(self.tab)
        self.gridWidget.setGeometry(QtCore.QRect(0, 0, 500, 600))
        self.gridWidget.setMinimumSize(QtCore.QSize(500, 600))
        self.gridWidget.setMaximumSize(QtCore.QSize(500, 600))
        self.gridWidget.setStyleSheet("font: 63 12pt \"Segoe UI Semibold\";")
        self.gridWidget.setObjectName("gridWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.sb1 = QtWidgets.QSpinBox(self.gridWidget)
        self.sb1.setEnabled(False)
        self.sb1.setMinimumSize(QtCore.QSize(70, 20))
        self.sb1.setMaximumSize(QtCore.QSize(70, 20))
        self.sb1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.sb1.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.sb1.setMinimum(1)
        self.sb1.setMaximum(100)
        self.sb1.setObjectName("sb1")
        self.gridLayout.addWidget(self.sb1, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridWidget)
        self.label_2.setMinimumSize(QtCore.QSize(80, 80))
        self.label_2.setMaximumSize(QtCore.QSize(80, 80))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:/Users/hofi/Desktop/11.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setWordWrap(False)
        self.label_2.setOpenExternalLinks(False)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridWidget)
        self.label.setMinimumSize(QtCore.QSize(170, 80))
        self.label.setMaximumSize(QtCore.QSize(150, 80))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridWidget)
        self.label_3.setMinimumSize(QtCore.QSize(170, 80))
        self.label_3.setMaximumSize(QtCore.QSize(160, 80))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridWidget)
        self.label_6.setMinimumSize(QtCore.QSize(170, 80))
        self.label_6.setMaximumSize(QtCore.QSize(150, 80))
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 1, 1, 1)
        self.sb2 = QtWidgets.QSpinBox(self.gridWidget)
        self.sb2.setEnabled(False)
        self.sb2.setMinimumSize(QtCore.QSize(70, 20))
        self.sb2.setMaximumSize(QtCore.QSize(70, 20))
        self.sb2.setMinimum(1)
        self.sb2.setMaximum(100)
        self.sb2.setObjectName("sb2")
        self.gridLayout.addWidget(self.sb2, 2, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridWidget)
        self.label_5.setMinimumSize(QtCore.QSize(80, 80))
        self.label_5.setMaximumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        font.setKerning(False)
        self.label_5.setFont(font)
        self.label_5.setText("")
        #self.label_5.setPixmap(QtGui.QPixmap("../../Pictures/Saved Pictures/skala_vershina_relef_167142_1920x1080.jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.cb2 = QtWidgets.QCheckBox(self.gridWidget)
        self.cb2.setMinimumSize(QtCore.QSize(15, 15))
        self.cb2.setMaximumSize(QtCore.QSize(15, 15))
        self.cb2.setText("")
        self.cb2.setObjectName("cb2")
        self.gridLayout.addWidget(self.cb2, 2, 2, 1, 1)
        self.cb3 = QtWidgets.QCheckBox(self.gridWidget)
        self.cb3.setMinimumSize(QtCore.QSize(15, 15))
        self.cb3.setMaximumSize(QtCore.QSize(15, 15))
        self.cb3.setText("")
        self.cb3.setObjectName("cb3")
        self.gridLayout.addWidget(self.cb3, 3, 2, 1, 1)
        self.cb4 = QtWidgets.QCheckBox(self.gridWidget)
        self.cb4.setMinimumSize(QtCore.QSize(15, 15))
        self.cb4.setMaximumSize(QtCore.QSize(15, 15))
        self.cb4.setText("")
        self.cb4.setObjectName("cb4")
        self.gridLayout.addWidget(self.cb4, 4, 2, 1, 1)
        self.sb4 = QtWidgets.QSpinBox(self.gridWidget)
        self.sb4.setEnabled(False)
        self.sb4.setMinimum(1)
        self.sb4.setMaximum(100)
        self.sb4.setObjectName("sb4")
        self.gridLayout.addWidget(self.sb4, 4, 3, 1, 1)
        self.sb3 = QtWidgets.QSpinBox(self.gridWidget)
        self.sb3.setEnabled(False)
        self.sb3.setMinimum(1)
        self.sb3.setMaximum(100)
        self.sb3.setObjectName("sb3")
        self.gridLayout.addWidget(self.sb3, 3, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridWidget)
        self.label_8.setMinimumSize(QtCore.QSize(170, 80))
        self.label_8.setMaximumSize(QtCore.QSize(150, 80))
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridWidget)
        self.label_7.setEnabled(True)
        self.label_7.setMinimumSize(QtCore.QSize(80, 80))
        self.label_7.setMaximumSize(QtCore.QSize(80, 80))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("31.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setWordWrap(False)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.sb5 = QtWidgets.QSpinBox(self.gridWidget)
        self.sb5.setEnabled(False)
        self.sb5.setMinimum(1)
        self.sb5.setMaximum(100)
        self.sb5.setObjectName("sb5")
        self.gridLayout.addWidget(self.sb5, 5, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridWidget)
        self.label_9.setMinimumSize(QtCore.QSize(80, 80))
        self.label_9.setMaximumSize(QtCore.QSize(80, 80))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("32.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 5, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridWidget)
        self.label_10.setMinimumSize(QtCore.QSize(170, 80))
        self.label_10.setMaximumSize(QtCore.QSize(150, 80))
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 5, 1, 1, 1)
        self.cb5 = QtWidgets.QCheckBox(self.gridWidget)
        self.cb5.setMinimumSize(QtCore.QSize(15, 15))
        self.cb5.setMaximumSize(QtCore.QSize(15, 15))
        self.cb5.setText("")
        self.cb5.setObjectName("cb5")
        self.gridLayout.addWidget(self.cb5, 5, 2, 1, 1)
        self.cb1 = QtWidgets.QCheckBox(self.gridWidget)
        self.cb1.setMinimumSize(QtCore.QSize(15, 15))
        self.cb1.setMaximumSize(QtCore.QSize(15, 15))
        self.cb1.setText("")
        self.cb1.setObjectName("cb1")
        self.gridLayout.addWidget(self.cb1, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridWidget)
        self.label_4.setMinimumSize(QtCore.QSize(80, 80))
        self.label_4.setMaximumSize(QtCore.QSize(80, 80))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("12.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.sb1.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.cb2.raise_()
        self.sb2.raise_()
        self.label_6.raise_()
        self.cb3.raise_()
        self.sb3.raise_()
        self.label_8.raise_()
        self.cb4.raise_()
        self.sb4.raise_()
        self.label_10.raise_()
        self.cb5.raise_()
        self.sb5.raise_()
        self.cb1.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_7.raise_()
        self.label_9.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setMinimumSize(QtCore.QSize(500, 600))
        self.tab_2.setMaximumSize(QtCore.QSize(500, 600))
        self.tab_2.setObjectName("tab_2")
        self.out = QtWidgets.QTextBrowser(self.tab_2)
        self.out.setGeometry(QtCore.QRect(22, 0, 450, 550))
        self.out.setMinimumSize(QtCore.QSize(450, 550))
        self.out.setMaximumSize(QtCore.QSize(450, 550))
        self.out.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.out.setObjectName("out")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Чизбургер с луком<br/>74 рубля</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Шефбургер Джуниор<br/>109 рублей</p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Шефбургер Джуниор<br/>острый<br/>109 рублей</p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Чай черный<br/>74 рубля</p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Кофе Капучино<br/>64 рубля</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
