# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setStyleSheet("background-color: rgb(105, 127, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setGeometry(QtCore.QRect(5, 220, 791, 361))
        self.table.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.horizontalWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalWidget.setGeometry(QtCore.QRect(10, 20, 781, 80))
        self.horizontalWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalWidget)
        self.label.setMinimumSize(QtCore.QSize(255, 50))
        self.label.setMaximumSize(QtCore.QSize(255, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.line_name = QtWidgets.QLineEdit(self.horizontalWidget)
        self.line_name.setMinimumSize(QtCore.QSize(255, 50))
        self.line_name.setMaximumSize(QtCore.QSize(255, 50))
        self.line_name.setObjectName("line_name")
        self.horizontalLayout.addWidget(self.line_name)
        self.button_name = QtWidgets.QPushButton(self.horizontalWidget)
        self.button_name.setMinimumSize(QtCore.QSize(255, 50))
        self.button_name.setMaximumSize(QtCore.QSize(255, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.button_name.setFont(font)
        self.button_name.setStyleSheet("background-color: rgb(157, 165, 213);")
        self.button_name.setObjectName("button_name")
        self.horizontalLayout.addWidget(self.button_name)
        self.horizontalWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalWidget1.setGeometry(QtCore.QRect(9, 120, 781, 80))
        self.horizontalWidget1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.horizontalWidget1.setObjectName("horizontalWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.horizontalWidget1)
        self.label_2.setMinimumSize(QtCore.QSize(70, 50))
        self.label_2.setMaximumSize(QtCore.QSize(70, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.line_year = QtWidgets.QLineEdit(self.horizontalWidget1)
        self.line_year.setMinimumSize(QtCore.QSize(100, 50))
        self.line_year.setMaximumSize(QtCore.QSize(100, 50))
        self.line_year.setObjectName("line_year")
        self.horizontalLayout_2.addWidget(self.line_year)
        self.label_3 = QtWidgets.QLabel(self.horizontalWidget1)
        self.label_3.setMinimumSize(QtCore.QSize(70, 50))
        self.label_3.setMaximumSize(QtCore.QSize(70, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.line_time = QtWidgets.QLineEdit(self.horizontalWidget1)
        self.line_time.setMinimumSize(QtCore.QSize(100, 50))
        self.line_time.setMaximumSize(QtCore.QSize(100, 50))
        self.line_time.setObjectName("line_time")
        self.horizontalLayout_2.addWidget(self.line_time)
        self.label_4 = QtWidgets.QLabel(self.horizontalWidget1)
        self.label_4.setMinimumSize(QtCore.QSize(70, 50))
        self.label_4.setMaximumSize(QtCore.QSize(70, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.combo = QtWidgets.QComboBox(self.horizontalWidget1)
        self.combo.setMinimumSize(QtCore.QSize(150, 50))
        self.combo.setMaximumSize(QtCore.QSize(150, 50))
        self.combo.setStyleSheet("background-color: rgb(203, 194, 207);")
        self.combo.setObjectName("combo")
        self.combo.addItem("")
        self.horizontalLayout_2.addWidget(self.combo)
        self.button_genre = QtWidgets.QPushButton(self.horizontalWidget1)
        self.button_genre.setMinimumSize(QtCore.QSize(183, 50))
        self.button_genre.setMaximumSize(QtCore.QSize(183, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.button_genre.setFont(font)
        self.button_genre.setStyleSheet("background-color: rgb(157, 165, 213);")
        self.button_genre.setObjectName("button_genre")
        self.horizontalLayout_2.addWidget(self.button_genre)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "!Enter movie name!"))
        self.button_name.setText(_translate("MainWindow", "!Press!"))
        self.label_2.setText(_translate("MainWindow", "Year"))
        self.label_3.setText(_translate("MainWindow", "Time"))
        self.label_4.setText(_translate("MainWindow", "Genres"))
        self.combo.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">Не выбрано</p></body></html>"))
        self.combo.setItemText(0, _translate("MainWindow", "не выбрано"))
        self.button_genre.setText(_translate("MainWindow", "!Press!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
