# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setGeometry(QtCore.QRect(10, 170, 781, 371))
        self.table.setMinimumSize(QtCore.QSize(781, 371))
        self.table.setMaximumSize(QtCore.QSize(781, 371))
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.horizontalWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalWidget.setGeometry(QtCore.QRect(10, 10, 781, 61))
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalWidget)
        self.label.setMinimumSize(QtCore.QSize(255, 40))
        self.label.setMaximumSize(QtCore.QSize(255, 40))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.line_name = QtWidgets.QLineEdit(self.horizontalWidget)
        self.line_name.setMinimumSize(QtCore.QSize(255, 40))
        self.line_name.setMaximumSize(QtCore.QSize(255, 40))
        self.line_name.setObjectName("line_name")
        self.horizontalLayout.addWidget(self.line_name)
        self.button_name = QtWidgets.QPushButton(self.horizontalWidget)
        self.button_name.setMinimumSize(QtCore.QSize(255, 40))
        self.button_name.setMaximumSize(QtCore.QSize(255, 40))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.button_name.setFont(font)
        self.button_name.setObjectName("button_name")
        self.horizontalLayout.addWidget(self.button_name)
        self.horizontalWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalWidget_2.setGeometry(QtCore.QRect(10, 80, 781, 61))
        self.horizontalWidget_2.setObjectName("horizontalWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.horizontalWidget_2)
        self.label_2.setMinimumSize(QtCore.QSize(80, 40))
        self.label_2.setMaximumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.line_year = QtWidgets.QLineEdit(self.horizontalWidget_2)
        self.line_year.setMinimumSize(QtCore.QSize(100, 40))
        self.line_year.setMaximumSize(QtCore.QSize(100, 40))
        self.line_year.setObjectName("line_year")
        self.horizontalLayout_2.addWidget(self.line_year)
        self.label_3 = QtWidgets.QLabel(self.horizontalWidget_2)
        self.label_3.setMinimumSize(QtCore.QSize(80, 40))
        self.label_3.setMaximumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.line_time = QtWidgets.QLineEdit(self.horizontalWidget_2)
        self.line_time.setMinimumSize(QtCore.QSize(100, 40))
        self.line_time.setMaximumSize(QtCore.QSize(100, 40))
        self.line_time.setObjectName("line_time")
        self.horizontalLayout_2.addWidget(self.line_time)
        self.label_4 = QtWidgets.QLabel(self.horizontalWidget_2)
        self.label_4.setMinimumSize(QtCore.QSize(80, 40))
        self.label_4.setMaximumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.combo = QtWidgets.QComboBox(self.horizontalWidget_2)
        self.combo.setMinimumSize(QtCore.QSize(0, 40))
        self.combo.setMaximumSize(QtCore.QSize(16777215, 40))
        self.combo.setObjectName("combo")
        self.combo.addItem("")
        self.horizontalLayout_2.addWidget(self.combo)
        self.button_genre = QtWidgets.QPushButton(self.horizontalWidget_2)
        self.button_genre.setMinimumSize(QtCore.QSize(0, 40))
        self.button_genre.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.button_genre.setFont(font)
        self.button_genre.setObjectName("button_genre")
        self.horizontalLayout_2.addWidget(self.button_genre)
        self.horizontalWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalWidget1.setGeometry(QtCore.QRect(10, 550, 781, 41))
        self.horizontalWidget1.setObjectName("horizontalWidget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalWidget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.button_add = QtWidgets.QPushButton(self.horizontalWidget1)
        self.button_add.setMinimumSize(QtCore.QSize(390, 38))
        self.button_add.setMaximumSize(QtCore.QSize(390, 38))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.button_add.setFont(font)
        self.button_add.setObjectName("button_add")
        self.horizontalLayout_3.addWidget(self.button_add)
        self.button_save = QtWidgets.QPushButton(self.horizontalWidget1)
        self.button_save.setMinimumSize(QtCore.QSize(380, 38))
        self.button_save.setMaximumSize(QtCore.QSize(380, 38))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.button_save.setFont(font)
        self.button_save.setObjectName("button_save")
        self.horizontalLayout_3.addWidget(self.button_save)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Введите название фильма"))
        self.button_name.setText(_translate("MainWindow", "Нажми"))
        self.label_2.setText(_translate("MainWindow", "Год"))
        self.label_3.setText(_translate("MainWindow", "Время"))
        self.label_4.setText(_translate("MainWindow", "Жанр"))
        self.combo.setItemText(0, _translate("MainWindow", "не выбрано"))
        self.button_genre.setText(_translate("MainWindow", "Нажми"))
        self.button_add.setText(_translate("MainWindow", "Добавить"))
        self.button_save.setText(_translate("MainWindow", "Изменить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
